version: ~> 1.0
import: Typeform/travis-shared-config:package-config.yml@master

language: node_js
node_js:
  - '10'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

cache: yarn

script:
  - yarn run lint

after_success:
  - yarn run travis-deploy-once "yarn run semantic-release"

notifications:
  email: false
