language: node_js
node_js:
  - '12'

# Travis runs on PUSH events ONLY in master branch. This does not affect to Travis running on PULL REQUEST event
branches:
  only:
    - master

cache: yarn

stages:
  - name: pull_request
    if: branch = master AND type = pull_request
  - name: release
    if: branch = master AND type = push

jobs:
  include:
    - stage: lint
      script: yarn run lint
    - stage: release
      before_script:
        - npm config set '//npm.pkg.github.com/:_authToken' ${GH_TOKEN}
        - npm config set registry https://npm.pkg.github.com/
      script:
        - yarn run lint
        - yarn run semantic-release
      after_success:
        - npm config set '//registry.npmjs.org/:_authToken' ${NPM_TOKEN}
        - npm config set registry https://registry.npmjs.org/
        - npm publish

notifications:
  email: false
