language: node_js
node_js:
  - '12'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

cache: yarn

stages:
  - lint
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: lint
      script: yarn run lint
    - stage: deploy
      script: yarn run lint
      before_deploy:
        - npm config set '//npm.pkg.github.com/:_authToken' ${GH_TOKEN}
        - npm config set registry https://npm.pkg.github.com/
      deploy:
        - provider: script
          skip_cleanup: true
          script:
            - yarn run semantic-release
            - npm config set '//registry.npmjs.org/:_authToken' ${NPM_TOKEN}
            - npm config set registry https://registry.npmjs.org/
            - npm publish

notifications:
  email: false
