name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

jobs:
  tests:
    runs-on: [ubuntu-latest]

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
